[package]
name = "HTTP-Server"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
dotenv = "0.15"
rand = "0.8"
sha2 = "0.10"
regex = "1.12.2"
xz2 = "0.1.7"
flate2 = "1.1.5"
uuid = { version = "1", features = ["v4"] }
serde_json = "1.0"
