pub static COMMANDS: &[&str] = &[
    "/fibonacci?num=N",
    "/createfile?name=filename&content=text&repeat=x",
    "/deletefile?name=filename",
    "/status",
    "/reverse?text=abcdef",
    "/toupper?text=abcd",
    "/random?count=n&min=a&max=b",
    "/timestamp",
    "/hash?text=someinput",
    "/simulate?seconds=s&task=name",
    "/sleep?seconds=s",
    "/loadtest?tasks=n&sleep=x",
    "/help",
];
